name: Biscred Regression Suite

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '45 6 * * *'

jobs:
  run-SeleniumTest:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Run Docker container
      run: |
        docker run -d --name my_container -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.21.0-20240522
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Print
      run: |
        ls -l
        cd JavaTestNgParellel
        ls -l
        type testng.xml
    - name: Build with Maven
      run: mvn test -Preg
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ExtentReport
        path: ./Reports/*.*
    - name: Stop Docker container
      if: always()
      run: |
        docker stop my_container
        docker rm my_container
